### ISSUE TITLE
Provide a GH action

### ISSUE THREAD

**Issue by inknos** [rpm-software-management/fedora-distro-aliases#6]
Hi,

I would benefit from an action that would look like this:
```yaml
- name: Get the correct Fedora Release from Bodhi
  uses: rpm-software-management/fedora-distro-aliases@v1
  with:
    fedora: fedora-latest
```
And with outputs the result of the query.

Would you consider something like this?

Thanks
